### ISSUE TITLE
Retrieve the current authenticated user in API route

### ISSUE THREAD

**Issue by hitostacha** [mtvbrianking/multi-auth#12]
I'm trying to retrieve the current authenticated user for a guard I set up using this, whenever I try calling a guard, say, it's named 'admin', I use `\Auth::guard('admin')->user();` , it works on web routes, but not on API routes, am I doing something wrong?

**Comment by mtvbrianking** [comment]
The admin guard is using `web` not `api` middleware

![image](https://user-images.githubusercontent.com/5412360/46454939-60aeb000-c7b1-11e8-97cd-7dcc0100ace6.png)
