### ISSUE TITLE
I have installed the multi cuth package now i want to remove it from my laravel application how do i do it

### ISSUE THREAD

**Issue by SayedAkhtar** [mtvbrianking/multi-auth#15]

**Comment by mtvbrianking** [comment]
## [Uninstall](https://github.com/mtvbrianking/multi-auth/blob/master/files.md#uninstalling)

- Uninstall the package using composer

`composer remove bmatovu/multi-auth`

- Reverse the physical changes manually

- You might need to reload the class map

`composer dump-autoload`

[Read more](https://github.com/mtvbrianking/multi-auth/blob/master/files.md#uninstalling)

**Comment by SayedAkhtar** [comment]
I am receiving Undefined offset:0 error

**Comment by mtvbrianking** [comment]
Which guards had you created with the package?

**Comment by SayedAkhtar** [comment]
Customer

**Comment by mtvbrianking** [comment]
The package creates physical file in your project, similar to when you scaffold the default [Laravel Authentication](https://laravel.com/docs/master/authentication#introduction).

Therefore you might want to remove those files; following the [changed/affected files guide](https://github.com/mtvbrianking/multi-auth/blob/master/files.md#file-change-log)

**Comment by SayedAkhtar** [comment]
I am getting the above said error after I changed all the affected files

**Comment by mtvbrianking** [comment]
Give more verbose regarding the error maybe then I can help.

**Comment by SayedAkhtar** [comment]
When I am trying to reload my page to the root directory it reports "Undefined
offset:0" that's it
