### ISSUE TITLE
Verified Controller Class not imported

### ISSUE THREAD

**Issue by xcobary** [mtvbrianking/multi-auth#23]
When a user clicks on verify email from his/her email, it throws a new exception that the verified controller class is not imported.

I had to manually go and import the class.

Thank you for the great work

**Comment by mtvbrianking** [comment]
Not sure how to replicate this issue,

But did you make use of the [Email Verification Guide](https://github.com/mtvbrianking/multi-auth/wiki/Email-Verification)?

Maybe we can start debugging from there

**Comment by xcobary** [comment]
I sure made use of the Email Verification Guide.

In the Verification Controller on line 74, there is a Verified Class. This class wasn't imported by default for my Laravel 5.8 install.

I fixed the problem by manually importing the Verified Class in the Verification Controller.

Great work, Brian

**Comment by mtvbrianking** [comment]
Thanks,

Will correct it in the package as well.
