### ISSUE TITLE
add role input button tor register method

### ISSUE THREAD

**Issue by asadghazanfary** [mtvbrianking/multi-auth#26]
how can i add **Role** radio button input to register blade?

i add radio button to register form like this:

`<div class="form-check form-check-inline">
                                            <input class="form-check-input" type="radio" name="role" id="inlineRadio1" value="client">
                                            <label class="form-check-label" for="inlineRadio1">1</label>
                                        </div>
                                        <div class="form-check form-check-inline">
                                            <input class="form-check-input" type="radio" name="role" id="inlineRadio2" value="translator">
                                            <label class="form-check-label" for="inlineRadio2">2</label>
                                        </div>`

but not exist in **$data** when i use **dd()** method.

i use required role validation for radio button but not work.

anybody help me

**Comment by mtvbrianking** [comment]
@asadghazanfary am afraid your inquiry is not directly related to this package, therefore, I can't be of help.

You might be better off asking the same question on forums like [StackOverflow](https://stackoverflow.com) or [Laracast](https://laracasts.com).
