### ISSUE TITLE
Change Directories

### ISSUE THREAD

**Issue by hananiamizrahi** [mtvbrianking/multi-auth#3]
Is there any way to remove from vendors how the image suggests these routes and files without affecting the functioning of the lib?
![image](https://user-images.githubusercontent.com/29582813/38365891-61031ca8-38b4-11e8-863b-1bbc68a3d04b.png)

**Comment by mtvbrianking** [comment]
I didn't get your question; "**any way to remove from vendors**", what do you wish to remove from vendor?

**Comment by hananiamizrahi** [comment]
I would like to get these directories inside src in vendor to put inside App, since when updating the view via composer, it updates the lib and I end up losing everything I did ... How to solve this?

**Comment by mtvbrianking** [comment]
Don't work from vendor, after installing the package and registering it in `config/app.php`, whole it functionality will be accessible to your app.

Therefore; just add your app logic in `app` directory

**Comment by hananiamizrahi** [comment]
@mtvbrianking As I explain, for some reason it was not added to the app folder. So, imagining a hypothetical situation, where this automated directory transfer does not work, however it has been installed and not `config/app.php`, how to do this transfer manually?

**Comment by mtvbrianking** [comment]
@hananiamizrahi am going to write a more detailed article on my [blog](http://bmatovu.com) on how to use the package. I will share by the end of day.

**Comment by mtvbrianking** [comment]
@hananiamizrahi I had some error in the readme file, my bad. 

I have corrected the file, and update the **artisan vendor:publish** options. and made a [new release](https://github.com/mtvbrianking/multi-auth/releases/tag/v1.0.3) `v1.0.3`.

Now you can simply run `composer update` and all should be fine.

Thank you so much for pointing out. Am sorry I misinterpreted you issue at first.

**Comment by hananiamizrahi** [comment]
@mtvbrianking 
There is some way to rename the controllers that are generated in the applications, it is much more recent 1.0.3, but when creating new routes protected by the administrator, they have the controllers still inside the vendor `vendor\Bmatovu\MultiAuth\Controladores\Admin` and maybe the ideal is that I can, in the `App` directory, configure my logics without using the namespace inside vendor...

**Comment by mtvbrianking** [comment]
@hananiamizrahi I will implement that as well, this week. Hopeful it should be ready by midweek.

**Comment by mtvbrianking** [comment]
@hananiamizrahi I under estimated the hill ahead so it too me a couple of more days to make the promised improvements.

Finally here is version: [v1.1.0](https://github.com/mtvbrianking/multi-auth/releases/tag/v1.1.0) with the promised improvements and more...

Thank you for your continued supported
