### ISSUE TITLE
Laravel 8 Compatibility

### ISSUE THREAD

**Issue by wandyyd** [mtvbrianking/multi-auth#30]
Hi there!

Just been wondering, are you/your team would be able to check the compatibility with Laravel 8?
I'm using this awesome package in a while on Laravel 7 and trying to upgrade to Laravel 8 via composer, but it seems give some warning/error.

<details>
<summary> composer update </summary>
<pre>
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove bmatovu/multi-auth v9.0.0
    - Conclusion: don't install laravel/framework v8.1.0
    - Conclusion: don't install laravel/framework v8.0.4
    - Conclusion: don't install laravel/framework v8.0.3
    - Conclusion: don't install laravel/framework v8.0.2
    - Conclusion: don't install laravel/framework v8.0.1
    - Installation request for bmatovu/multi-auth ^9.0 -> satisfiable by bmatovu/multi-auth[v9.0.0].
    - Conclusion: don't install laravel/framework v8.0.0
    - bmatovu/multi-auth v9.0.0 requires illuminate/support ^7.0 -> satisfiable by laravel/framework[v7.28.1], illuminate/support[7.x-dev, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.10.0, v7.10.1, v7.10.2, v7.10.3, v7.11.0, v7.12.0, v7.13.0, v7.14.0, v7.14.1, v7.15.0, v7.16.0, v7.16.1, v7.17.0, v7.17.1, v7.17.2, v7.18.0, v7.19.0, v7.19.1, v7.2.0, v7.2.1, v7.2.2, v7.20.0, v7.21.0, v7.22.0, v7.22.1, v7.22.2, v7.22.3, v7.22.4, v7.23.0, v7.23.1, v7.23.2, v7.24.0, v7.25.0, v7.26.0, v7.26.1, v7.27.0, v7.28.0, v7.28.1, v7.3.0, v7.4.0, v7.5.0, v7.5.1, v7.5.2, v7.6.0, v7.6.1, v7.6.2, v7.7.0, v7.7.1, v7.8.0, v7.8.1, v7.9.0, v7.9.1, v7.9.2].
    - Can only install one of: laravel/framework[8.x-dev, v7.28.1].
    - don't install illuminate/support 7.x-dev|don't install laravel/framework 8.x-dev
</pre>
</details>

Thank you 😄

**Comment by mtvbrianking** [comment]
@wandyyd I'll be adding support for Laravel 8 tomorrow via `laravel/ui` v3.x but I'm considering switching to `Laravel/jetstream` as recommended by the core Laravel them team.

**Comment by mtvbrianking** [comment]
@wandyyd I've pushed the initial release targeting Laravel v8.x

See [v10.0.0](https://github.com/mtvbrianking/multi-auth/releases/tag/v10.0.0)

**Comment by wandyyd** [comment]
Cool! Thanks for your effort @mtvbrianking 😄

**Comment by wandyyd** [comment]
Hi @mtvbrianking - I didn't want to open an issue, since it's not an issue anyway.
I just want to let you know, if you haven't yet get any update about Laravel 8 - here's the link [video](https://www.youtube.com/watch?v=L1FVdHdEm_8)
In-summary - they will keep supporting Laravel UI.

So, I'm just thinking that you can update the readme.md if you have sometime later, so it won't misleading newcomers in Laravel.

*A little question, are you (or your team) had some plan to create multi-auth using jetstream (fortify) pipeline?

Thank you! 😄

**Comment by mtvbrianking** [comment]
Hello @wandyyd, I plan on adding the new features that `laravel/fortify` has to offer, but I'm like to keep the `laravel/ui` kinda of scaffolding since I need to generate multiple sets of code for different guards.

However, this is target for the next Laravel release when not v8.x

**Comment by wandyyd** [comment]
I see.. Thanks for letting me know about the plan!
Best of luck for that! 😄
