### ISSUE TITLE
Remove registration routes from admin

### ISSUE THREAD

**Issue by idezigns** [mtvbrianking/multi-auth#32]
I want to remove the routes in admin section register, e.g; admin/register.

I know in regular Auth you can do Auth::routes(['register' => false]), what can we do aside from editing the register controller for it.

**Comment by mtvbrianking** [comment]
Just comment it out in the routes files. Usually; `routes/YOUR_GUARD.php`

**Comment by idezigns** [comment]
Lol, I did not even realize it was there, my bad thank you.
