### ISSUE TITLE
model created in wrong place

### ISSUE THREAD

**Issue by atomos1** [mtvbrianking/multi-auth#33]
**Models are created in the wrong place as you can see.**

_Student is a custom guard_
Laravel 8.10.0

![image](https://user-images.githubusercontent.com/73071807/96374738-d7d6f700-1174-11eb-8a2e-6bc2197b2184.png)

**Comment by mtvbrianking** [comment]
Let me look into it

**Comment by mtvbrianking** [comment]
Fix in (a28fa9b, [v10.3.0](https://github.com/mtvbrianking/multi-auth/releases/tag/v10.3.0))
