### ISSUE TITLE
Multi-auth is changing my guard name

### ISSUE THREAD

**Issue by atomos1** [mtvbrianking/multi-auth#34]
As you can see multi-auth is substituting "a" with "um" when adding new guard.

Laravel 8.10.0

![image](https://user-images.githubusercontent.com/73071807/96375714-dd374000-117a-11eb-8be5-b8d16333ef73.png)

**Comment by mtvbrianking** [comment]
Ohhhh....

`Agenzia to Agenzium`

It's try to determine the singular of the guard

Like: `Admins to Admin`

**Comment by mtvbrianking** [comment]
See [`parseName($name)`](https://github.com/mtvbrianking/multi-auth/blob/master/src/Console/MultiAuthInstallCommand.php#L211)

![image](https://user-images.githubusercontent.com/5412360/96376126-c8ac7500-1185-11eb-9260-ae2e33feb7e3.png)
