### ISSUE TITLE
Multi - auth / Multi- tenancy

### ISSUE THREAD

**Issue by samuelvincenzome** [mtvbrianking/multi-auth#38]
Hello everybody, How are you?

I would like to know if it is possible to use this multi-authentication package with a multi-tenancy system.
Multi tenancy will be per subdomain.

thanks

Samuel de Vincenzo

**Comment by mtvbrianking** [comment]
@samuelvincenzome I've never used the package in a multi-tenancy setup but I don't see a reason why it would fail.

I'd you appreciate you trying it out and sharing your experience.

Thanks

**Comment by samuelvincenzome** [comment]
hello @mtvbrianking. Thanks for the feedback. I will test and go over how was my experience in implementing Multi Rental.
Do I leave this ticket open or open another?

**Comment by mtvbrianking** [comment]
Let's keep the discussion on this ticket.

I'll leave it open for as long as it's still active

**Comment by mtvbrianking** [comment]
I'll be closing this thread since it's no longer active.
