### ISSUE TITLE
Hi, any update on using this multi-auth with laravel/fortify?

### ISSUE THREAD

**Issue by iabduul7** [mtvbrianking/multi-auth#41]

**Comment by mtvbrianking** [comment]
I'll like switch from Laravel UI to fortify in the next major release (targeting Laravel 9).

**Comment by ankurk91** [comment]
i would recommend to have a separate package for fortify and leave this package for laravel-ui updates

**Comment by mtvbrianking** [comment]
@iabduul7 `laravel/fortify` isn't the best approach for this package

@ankurk91 I intend to switch to `laravel/breeze` when time allow

**Comment by iabduul7** [comment]
Understood, have a nice day... 
For anyone looking to use multi-auth for Laravel/fortify, it is recommended to use Laravel Breeze

**Comment by mtvbrianking** [comment]
Breeze has not multi-auth support out of the box. 

But Fortify approach is more complex to adopt it for multi-auth thus making it harder to maintain in practice.

Laravel Breeze / UI are better picks for the same job.
