### ISSUE TITLE
Issue with laravel 9

### ISSUE THREAD

**Issue by m4tt86** [mtvbrianking/multi-auth#45]
When I launch the `composer require bmatovu/multi-auth` command I receive the following error: 

`Problem 1
    - Root composer.json requires bmatovu/multi-auth ^10.4 -> satisfiable by bmatovu/multi-auth[v10.4.0].
    - bmatovu/multi-auth v10.4.0 requires illuminate/auth ^8.0 -> found illuminate/auth[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require bmatovu/multi-auth:*" to figure out if any version is installable, or "composer require bmatovu/multi-auth:^2.1" if you know which you need.`

**Comment by mtvbrianking** [comment]
Hi @m4tt86,

I hadn't added Laravel 9 support yet.

I'll do so probably over the weekend

**Comment by m4tt86** [comment]
ok, thanks

**Comment by mtvbrianking** [comment]
[Added support for Laravel v9 with Bootstrap v5](https://github.com/mtvbrianking/multi-auth/releases/tag/v11.0.0)
