### ISSUE TITLE
Protect Routes

### ISSUE THREAD

**Issue by hananiamizrahi** [mtvbrianking/multi-auth#5]
For some reason I can not protect the routes I've created in Routes / web.php, what do you suggest?

Problem: If I access a url without being logged in, the system should redirect my login screen, right? If I access Admin / Home works, however, for all other routes created it looks like it's having a bypass before it reaches the middleware it protects. What to do in this case?

**Comment by mtvbrianking** [comment]
@hananiamizrahi you can apply the necessary middleware; including the guard

Ref: https://github.com/mtvbrianking/multi-auth/blob/v1.1.6/stubs/Controllers/HomeController.stub#L19

In your case it might be something like: 

`admin.auth:admin` where; `admin.auth` is your middleware, and `admin` is your guard

Confirm the middleware was applied to your routes by running 

`php artisan route:list`
