### ISSUE TITLE
MultiAuthServiceProvides NotFound.

### ISSUE THREAD

**Issue by hananiamizrahi** [mtvbrianking/multi-auth#6]
How can i sold this?

![image](https://user-images.githubusercontent.com/29582813/43203388-7483a710-8ff4-11e8-8253-4944a20fe2e9.png)

**Comment by mtvbrianking** [comment]
I changed the service provider path way back in v1.1.0 to much the popular Laravel packages' directory structure and setup.

if you **[compare](https://github.com/mtvbrianking/multi-auth/compare/v1.0.3...v1.1.0#diff-0730bb7c2e8f9ea2438b52e419dd86c9R20)** the branches [v1.0.3](https://github.com/mtvbrianking/multi-auth/blob/v1.0.3/readme.md) vs [v1.1.0](https://github.com/mtvbrianking/multi-auth/blob/v1.1.0/readme.md) you will see this change

Have you tried `composer dump-autoload` or `composer clear-cache`

If you registered the service provider manually in `config/app.php` just update it as below

![image](https://user-images.githubusercontent.com/5412360/43220575-0eff3030-9053-11e8-9f9b-7f99e0ac6283.png)

![image](https://user-images.githubusercontent.com/5412360/43220198-290907ea-9052-11e8-93d0-061468bd546c.png)

**Comment by hananiamizrahi** [comment]
How can i solve this problem? Composer Update? but it doesnt work...

**Comment by mtvbrianking** [comment]
**Try to clear cache like...**

`composer dump-autoload -o && artisan cache:clear && artisan config:clear`
