### ISSUE TITLE
How do I retrieve login information from the admin?

### ISSUE THREAD

**Issue by hananiamizrahi** [mtvbrianking/multi-auth#7]
To get the information of the common logged-in user I use _Auth::user()_ but to get those from the admin I still do not know how to do, is there any way?

**Comment by mtvbrianking** [comment]
Yes, you may specify the guard instance you would like to use:

`Auth::guard(`**{guard}**`)->user()->name` like `Auth::guard('admin')->user()->name`

[Read more...](https://laravel.com/docs/5.6/authentication#authenticating-users)
